apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policies
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/michaelkotelnikov/helm-rhacm-policies.git
      revision: master
      directories:
      - path: policies/values/*
  template:
    metadata:
      name: 'policy-{{path.basename}}'
    spec:
      project: policies
      source:
        repoURL: https://github.com/michaelkotelnikov/helm-rhacm-policies.git
        targetRevision: master
        path: policies/
        helm:
          valueFiles:
          - 'values/{{path.basename}}/values.yaml'
      destination:
        name: 'local-cluster'
        namespace: rhacm-policies
      syncPolicy:
        automated:
          prune: false
          selfHeal: true